spring:
  application:
    name: api

  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    generate-unique-name: false
    name: delivery
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

logging:
  level:
    com.fujitsu.api: DEBUG

weather:
  data:
    url: https://www.ilmateenistus.ee/ilma_andmed/xml/observations.php
  cron:
    expression: 0 15 * * * *
